### ISSUE TITLE
Is apm code blocking the main app code?

### ISSUE THREAD

**Issue by HazemKhaled** [kschingiz/meteor-elastic-apm#2]
For some reason my apm-server crash then I can see app performance very bad, so, I think the package code blocking the app code, is it! Can we consider it as an issue?

**Comment by kschingiz** [comment]
@HazemKhaled 
Can you please attach crash logs here? I didn't see any performance troubles in my test projects. Maybe I need to test it in more complicated projects. Will do that soon.

**Comment by HazemKhaled** [comment]
@kschingiz thanks for fast reply, can't see it's crashing, but i've some errors, even with active: false

```W20181008-17:13:49.501(3)? (STDERR) /Users/USER/.meteor/packages/promise/.0.11.1.glfzc8.h4vbb++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:218
W20181008-17:13:49.501(3)? (STDERR)       throw error;
W20181008-17:13:49.502(3)? (STDERR)       ^
W20181008-17:13:49.502(3)? (STDERR)
W20181008-17:13:49.502(3)? (STDERR) TypeError: Cannot read property 'end' of null
W20181008-17:13:49.502(3)? (STDERR)     at Session.sessionProto.protocol_handlers.unsub (packages/kschingiz:meteor-elastic-apm/hijack/session.js:72:16)
W20181008-17:13:49.502(3)? (STDERR)     at packages/ddp-server/livedata_server.js:559:43```

**Comment by HazemKhaled** [comment]
So, I got it, [this line](https://github.com/kschingiz/meteor-elastic-apm/blob/master/meteor-elastic-apm.js#L20) logged even when I removed `Agent.start` and also removed `import Agent from 'meteor/kschingiz:meteor-elastic-apm'`, cos simply this is on `MeteorX.onReady` not when we trigger start.

I think we need to extend start function to let this package run only after trigger start, and the use case for that, I had to remove this package on localhost, since i don't want track it.

```
// Add this to the VERY top of the first file loaded in your app
require('elastic-apm-node').start({
  // Only activate the agent if it's running in production
  active: process.env.NODE_ENV === 'production'
})
```

**Comment by kschingiz** [comment]
Yes, you are right, we are starting to listen methods before `agent.start` is called. Will fix it soon

**Comment by kschingiz** [comment]
@HazemKhaled I have fixed this. Thanks for your help!
