### ISSUE TITLE
Remove `node_modules` folder before publishing this package.

### ISSUE THREAD

**Issue by SimonSimCity** [kschingiz/meteor-elastic-apm#22]
When publishing a package in Meteor, the `node_modules` folder is included in the final package. This blows up this extension up to 131.5 MB in a demeteorized instance.

I could reduce the size down to 6.6 MB by fully removing the `node_modules` folder before building the application.

**Comment by kschingiz** [comment]
@SimonSimCity I have published new version 2.2.2 which does not include `.npm` and `node_modules` and with your fixes https://github.com/kschingiz/meteor-elastic-apm/pull/23

Thanks!

**Comment by SimonSimCity** [comment]
Any plans on how to avoid this in the future? I know other package owners started writing a command into their `package.json` which ensures that these things are in order. I at least think it would be good to ensure this doesn't happen again.

**Comment by kschingiz** [comment]
@SimonSimCity yeah, I will create a script in package.json:
```
"meteor-publish": "rm -rf ./node_modules && meteor publish"
```

and publish the package:
```
npm run meteor-publish
```
