### ISSUE TITLE
Span "sending" on transaction for HTTP requests is misleading

### ISSUE THREAD

**Issue by SimonSimCity** [kschingiz/meteor-elastic-apm#25]
On transactions of HTTP requests this package creates a span from the `finish` to the `close` event of the socket of the response and calls this "sending": https://github.com/kschingiz/meteor-elastic-apm/blob/f50b5bf399214643e49224561658e8adcd8c0278/instrumenting/http-in.js#L11-L36

This is quite misleading, because the documentation by the node package `http` states:
> __Event: 'finish'__
> _Added in: v0.3.6_
> Emitted when the response has been sent. More specifically, this event is emitted when the last segment of the response headers and body have been handed off to the operating system for transmission over the network. It does not imply that the client has received anything yet.

https://nodejs.org/api/http.html#http_event_finish

... and the documentation by the node package `Net` states the following for the `close` event on an `net.Socket` instance:

> __Event: 'close'__
> _Added in: v0.1.90_
>  - hadError <boolean> true if the socket had a transmission error.
> 
> Emitted once the socket is fully closed. The argument hadError is a boolean which says if the socket was closed due to a transmission error.

https://nodejs.org/api/http.html#http_event_close_1

When putting all these pieces together, it explains why the requests now always log the `sending` span on 5,001 ms.

Meteor sets a short-socket-timeout - as they call it - of 5 seconds: 
https://github.com/meteor/meteor/blob/05e5cb9105caaba7f5444fe088d0878a79a147a5/packages/webapp/webapp_server.js#L24

https://github.com/meteor/meteor/blob/05e5cb9105caaba7f5444fe088d0878a79a147a5/packages/webapp/webapp_server.js#L1024-L1030

I didn't notice this before because the software we're using to connect to our server closes the connection immediately after the request is done. But now, that we're using a load-balancer, the connection is kept open by the load-balancer, who doesn't close it when the software, actually communicating with the server, closes the connection.

The idea would work in a case where the server wouldn't keep the connection open, but since he does, I don't see a way yet to measure the actual time needed to send the request, but I'd rather just remove this.

**EDIT:** It's even worse for requests where the TCP timeout was reset. They sometimes last for 15sec even though it's just the TCP connection which is re-used for a different request, which is - and should be - logged separately.

**Comment by kschingiz** [comment]
@SimonSimCity I fixed this in this PR: #28 
I will merge when I complete with http-in and http-out tests.
Thanks!
